config/routes.rb
Rails.application.routes.draw do

get 'locations/index'
post 'locations/index'
get 'locations/show'
get 'locations/new'

resources :locations

  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
require 'rubygems'
require 'json'
require 'nokogiri'
require 'net/http'
class Location < ApplicationRecord
   self.ignored_columns = %w(class)

VALID_URL_REGEX = /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i
validates :url, presence: true, format: { with: VALID_URL_REGEX }
before_save :getdata
geocoded_by :ip
after_validation :geocode


private
def getdata

uri = ARGV[0]
response = Net::HTTP.get(URI(url))
json = JSON.parse(response)
 
doc = Nokogiri::HTML(response)
doc.at_css('title').text
doc.to_html
end


end



 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController


	  def index
      if params[:search].present?
      @locations = Location.search(params[:search])
    else
        @locations = Location.all
   end
    end

    def show
    @location = Location.find(params[:id])
    render :show => @location 
    end

  def new
     @location = Location.new
  end



  def create
 
     @location = Location.new(allowed_params)
     if @location.save
      redirect_to @location, :notice => "Successfully created location"
   else
      render :index
    end
  end


private

def search_params
  params.require(:search).permit(:id)
end




def allowed_params
    params.require(:location).permit(:id, :url, :ip, :email, :title, :country, :city, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/download/create.html.erb
<h1>Download#create</h1>
<p>Find me in app/views/download/create.html.erb</p>

app/views/download/index.html.erb
<h1>Download#index</h1>
<p>Find me in app/views/download/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>
<
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
     
   
   
<%= yield %>
   
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/locations/index.html.erb
  <%#= form_tag locations_path, :method => :get do %> 
  <%= form_for Location.new, url: locations_path, :method => :get do |f| %>
    <p>
     <%= f.text_field :search, value: params[:search] %> 
      <%= f.submit "Search", :name => :nil %> 
    </p>
 <% end %>

<table>
   <tr>
     <th>Website Url</th> 
     <th>Email</th>
     <th>Title</th>
     <th>Latitude</th>
     <th>Longitude</th> 
     <th>City</th>
     <th>Country</th>
    </tr>
   <%= @locations.each do |location| %>
     <tr>
        <td><%= location.url %></td> 
        <td><%= location.email %></td> 
        <td><%= location.title %></td> 
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td> 
        <td><%= location.city %></td>
        <td><%= location.country %></td>
        <td><%= link_to "Show", location_url(location) %></td>
        <td><%= link_to "Edit", edit_location_path(location) %></td> 
        <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td> 
      </tr>
   <% end %>
 </table> 

  <p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<p id="notice"><%= notice %></p>

  <%= form_for Location.new, url: locations_path do |f| %>
    <p> 
      <%= f.label :url %><br /> 
      <%= f.text_field :url, class: 'form-control' %> 
    </p>
   <p>
      <%= f.label :latitude %><br /> 
      <%= f.text_field :latitude, class: 'form-control' %>
   </p> 
    <p> 
      <%= f.label :longitude %><br />
      <%= f.text_field :longitude, class: 'form-control' %> 
    </p> 
        <p> 
      <%= f.label :city %><br /> 
      <%= f.text_field :city, class: 'form-control' %> 
    </p>
        <p> 
      <%= f.label :country %><br /> 
      <%= f.text_field :country, class: 'form-control' %> 
    </p>
           <p> 
      <%= f.label :email %><br /> 
      <%= f.text_field :email, class: 'form-control' %> 
    </p>
           <p> 
      <%= f.label :title %><br /> 
      <%= f.text_field :title, class: 'form-control' %> 
    </p>
    <p><%= f.submit %></p>
 <% end %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
   <strong>Website Url:</strong >
   <%= @location.url %> 
  </p> 
    <p>
   <strong>Email:</strong >
   <%= @location.email %> 
  </p>
    <p>
   <strong>Title:</strong >
   <%= @location.title %> 
  </p>
 <p> 
    <strong>Latitude:</strong> 
    <%= @location.latitude %> 
  </p>
 <p>
   <strong>Longitude:</strong>
   <%= @location.longitude %> 
  </p> 
    <p>
   <strong>City:</strong >
   <%= @location.city %> 
  </p> 
    <p>
   <strong>Country:</strong >
   <%= @location.country %> 
  </p> 

<p> 
    <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> | 
    <%= link_to "View All", locations_path %> 
  </p>